Adding v3 Changes

diff --git a/.github/workflows/deployment.yaml b/.github/workflows/deployment.yaml
--- a/.github/workflows/deployment.yaml
+++ b/.github/workflows/deployment.yaml
@@ -25,8 +25,9 @@ jobs:
       # 3️⃣ Deploy Django app
       - name: Deploy to Hostinger VPS
         run: |
+          echo "~/.ssh/id"
           ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_HOST }} 'bash -s' << 'ENDSSH'
-            set -e  # Exit immediately if a command fails
+            set -e  # Exit immediately if a command Fails
 
             echo "➡️ Moving to project directory"
             cd /var/www-data/Updated_Advitum-Healthcare
